---
title: "Introduction"
  subtitle: "R for Data Science"
  date: "9/19/2025"
format: html
editor: visual
---

## Introduction

First you must **import** your data into R. Once you've imported your data, you **tidy** it. Tidying your data means storing it in a consistent form that matches the semantics of the dataset with how it is stored. When your data is tidy, each column is a variable and each row is an observation. Once you have tidy data, a common next step is to **transform** it. Transformation includes narrowing in on observations of interest, creating new variables that are functions of existing variables, and calculating a set of summary statistics. Together, tidying and transforming are called **wrangling**. Once you have tidy data with the variables you need, there are two main engines of knowledge generation: **visualization and modeling.** Visualization will show you things you did not expect or raise new questions about the data. Models are complementary tools to visualization. Once you have made your questions, you can use a model to answer them. Models are fundamentally mathematical or computational tools. The last step of data science is **communication**. It doesn’t matter how well your models and visualization have led you to understand the data unless you can also communicate your results to others.

Summary: Data Science Process

1.  Import
2.  Tidy
3.  Transform
4.  Visualization and Modeling
5.  Communication

An R **package** is a collection of functions, data, and documentation that extends the capabilities of base R.

```{r}
install.packages() #install packages

library() #load packages

#tidyverse() loads nine packages: dplyr, forcats, ggplot2, lubridate, purrr, readr, stringr, tibble, tidyr. 
```

### Book Outline

Four chapters on the tools of data science:

Ch. 1: Data Visualization, Ch. 3: Data Transformation, Ch. 5: Data tidying, & Ch. 7: Data import

Nested among these chapters are four other chapters that focus on your R workflow:

Ch. 2: Workflow: basics, Ch. 4: code style, Ch. 6: Workflow: scripts and projects, Ch. 8: Workflow: getting help.
